#!/usr/bin/env python3
"""Close a report window at a release, and freeze the editions.

A release is the moment an in-flight report stops describing "what is coming"
and starts being the permanent record of "what shipped". This does the
mechanical half of that transition:

1. Copy each anchored report into ``docs/reports/releases/<tag>/``, re-stamped
   for the **released** window (``<prev tag>..<tag>``).
2. Re-anchor ``docs/reports/regular/`` to the new in-flight window, which now
   opens at the tag just cut.
3. Rebuild the archive index so the frozen editions are discoverable.

The narrative half — rewriting each report's prose to describe the closing
window in the past tense — is not mechanical and is not done here. Do it before
running this, or the frozen edition will carry a window it does not describe.

**Frozen editions are never edited again.** A correction to a shipped release's
report goes in an ``## Errata`` block on the *current* in-flight edition, naming
the release it corrects. Rewriting a frozen edition destroys the audit trail the
anchoring exists to create — which is the only reason to anchor at all.

Usage:  python scripts/docs/freeze_release.py --tag v1.4.0 [--dry-run]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.docs import frontmatter, release_window  # noqa: E402
from scripts.output import detail, fail, item, ok, step, warn  # noqa: E402
from scripts.paths import PROJECT_ROOT, REGULAR_DIR, RELEASES_DIR  # noqa: E402


def _rebuild_index() -> None:
    """Regenerate `docs/reports/releases/README.md` from what is on disk.

    Read from the directory rather than appended to, for the same reason the
    other indexes are: an appended index records what somebody remembered to
    add, and a rebuilt one records what is actually there.
    """
    editions = {}
    for path in sorted(RELEASES_DIR.glob("*/*.md")):
        editions.setdefault(path.parent.name, []).append(path.name)

    lines = [
        "<!-- GENERATED by scripts/docs/freeze_release.py — do not hand-edit. -->",
        "",
        "# Release Report Archive — Frozen Editions",
        "",
        "One immutable directory per release tag, each holding the reports as they",
        "described exactly what shipped in that release (`<prev tag>..<tag>`).",
        "",
        "**Never edit anything in here.** A correction to a shipped release's report goes",
        "in an `## Errata` block on the *current* in-flight edition, naming the release it",
        "corrects. Rewriting a frozen edition destroys the audit trail the anchoring exists",
        "to create.",
        "",
    ]

    if not editions:
        lines += ["_No releases frozen yet._", ""]
    else:
        # Newest first: a reader almost always wants the last release.
        for tag in sorted(editions, reverse=True):
            lines += [f"## {tag}", ""]
            for name in sorted(editions[tag]):
                lines.append(f"- [{name}]({tag}/{name})")
            lines.append("")

    RELEASES_DIR.mkdir(parents=True, exist_ok=True)
    (RELEASES_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--tag", required=True, help="the release tag whose window is closing")
    parser.add_argument("--dry-run", action="store_true", help="show what would happen, changing nothing")
    args = parser.parse_args()

    if args.tag not in release_window.tags():
        fail(f"unknown release tag: {args.tag}")
        detail("Freeze runs AFTER the tag exists — it records what shipped, not what will.")
        return 1

    closing = release_window.window(args.tag)
    destination = RELEASES_DIR / args.tag

    if destination.exists() and not args.dry_run:
        fail(f"{destination.relative_to(PROJECT_ROOT)} already exists — this release is already frozen.")
        detail("Frozen editions are never rewritten. A correction goes in an ## Errata block")
        detail("on the current in-flight edition, naming the release it corrects.")
        return 1

    step(f"closing {closing['commit_range']} ({closing['commits']} commits) as {args.tag}")

    frozen = []
    for name in release_window.ANCHORED_REPORTS:
        source = REGULAR_DIR / name
        if not source.exists():
            warn(f"{name} is anchored but missing from regular/ — skipping")
            continue
        item(f"freeze {name}")
        if args.dry_run:
            frozen.append(name)
            continue

        data, body = frontmatter.read(source)
        data.update({k: closing[k] for k in ("release", "previous_release", "commit_range", "status", "generated")})
        # Rewrite the prose window line to the CLOSED range, so the frozen file
        # is self-describing even if it is ever read outside the repo.
        body = release_window._WINDOW_LINE.sub(release_window._prose(closing), body, count=1)
        destination.mkdir(parents=True, exist_ok=True)
        frontmatter.write(destination / name, data, body)
        frozen.append(name)

    if args.dry_run:
        detail()
        step(f"(dry run) would freeze {len(frozen)} report(s) into docs/reports/releases/{args.tag}/")
        step("(dry run) would then re-anchor regular/ and rebuild the index")
        return 0

    # The in-flight window now opens at the tag just cut.
    detail()
    step("re-anchoring docs/reports/regular/ to the new in-flight window")
    if release_window.apply() != 0:
        return 1

    _rebuild_index()

    detail()
    ok(f"froze {len(frozen)} report(s) into docs/reports/releases/{args.tag}/")
    detail("Nothing was committed — read the diff, then commit as one `docs(reports):` change.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
