#!/usr/bin/env python3
"""Rebuild ``docs/TODO/README.md`` — the human-readable holding tank.

Sections are ordered by *what a reader does with them*, not alphabetically:
what needs your decision, what an agent can take, what is moving, and then the
reference lists. Each gated section leads with the gate, so plans that unblock
together sit together.

The 🚀 Ready section is the only one rendered in **run order** — it is the one
section that is a queue rather than a list, and it imports the same sort key the
queue's consumer uses (``queue_order.run_order``) so the published order is the
real one.

Usage:  python scripts/docs/rebuild_todo_readme.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, List

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.docs import plans  # noqa: E402
from scripts.docs.queue_order import UNORDERED, queue_position, run_order  # noqa: E402
from scripts.output import fail, ok  # noqa: E402
from scripts.paths import TODO_DIR  # noqa: E402

README_PATH = TODO_DIR / "README.md"

STATUS_HEADINGS = [
    (
        "in-review",
        "🔎 Awaiting Your Review",
        "Implemented and out for review — read the PR, then file the plan (or send it back).",
    ),
    (
        "ready",
        "🚀 Ready for Agent",
        "Every decision made and the spec complete — ready to hand to an agent end to end.",
    ),
    ("in-progress", "🟡 In Progress", "Actively being worked; partially shipped."),
    ("planned", "🔴 Planned", "Not started — intended future work."),
    ("blocked", "⛔ Blocked", "Startable or code-complete, gated on an external prerequisite."),
    ("shelved", "🟣 Shelved", "Built but intentionally parked behind a flag — each has an un-shelve plan."),
    ("deferred", "🟢 Deferred Follow-ups", "Backlog carved off completed work; revisit as capacity allows."),
]

GATE_LABELS = {
    "none": "✅ No gate",
    "time-window": "⏳ Time window",
    "owner-ops": "🖧 Host/ops change",
    "owner-cloud": "☁️ Cloud apply",
    "product-decision": "🧭 Product decision",
    "upstream": "🔗 Upstream",
    "unclassified": "❓ Not stated",
}


def _cell(text: str) -> str:
    """Escape pipes so a summary containing one cannot break the table."""
    return str(text).replace("|", "\\|").strip() or "—"


def _link(plan: plans.Plan) -> str:
    return f"[{_cell(plan.title)}]({plan.path.name})"


def _ready_table(items: List[plans.Plan]) -> Iterable[str]:
    yield "| Queue | Plan | Priority | Updated | Summary |"
    yield "| ----- | ---- | -------- | ------- | ------- |"
    for plan in sorted(items, key=lambda p: run_order(p.to_entry())):
        pos = queue_position(plan.to_entry())
        yield (
            f"| {'—' if pos == UNORDERED else pos} | {_link(plan)} | {plan.priority} "
            f"| {_cell(plan.updated)} | {_cell(plan.summary)} |"
        )


def _gated_table(items: List[plans.Plan]) -> Iterable[str]:
    yield "| Gate | Plan | Priority | Updated | Summary |"
    yield "| ---- | ---- | -------- | ------- | ------- |"
    for plan in sorted(items, key=lambda p: (str(p.blocked_on), p.slug)):
        yield (
            f"| {GATE_LABELS.get(str(plan.blocked_on), '❓ Not stated')} | {_link(plan)} "
            f"| {plan.priority} | {_cell(plan.updated)} | {_cell(plan.summary)} |"
        )


def _plain_table(items: List[plans.Plan]) -> Iterable[str]:
    yield "| Plan | Priority | Updated | Summary |"
    yield "| ---- | -------- | ------- | ------- |"
    for plan in sorted(items, key=lambda p: p.slug):
        yield f"| {_link(plan)} | {plan.priority} | {_cell(plan.updated)} | {_cell(plan.summary)} |"


def _review_table(items: List[plans.Plan]) -> Iterable[str]:
    yield "| Plan | Review PR | Updated | Summary |"
    yield "| ---- | --------- | ------- | ------- |"
    for plan in sorted(items, key=lambda p: p.slug):
        yield f"| {_link(plan)} | {_cell(plan.review_pr or '—')} | {_cell(plan.updated)} | {_cell(plan.summary)} |"


def build() -> str:
    all_plans = plans.scan(TODO_DIR)
    # Agent-managed docs are derived artifacts that a job rewrites wholesale.
    # They get their own heading whatever status they wear, because one listed
    # beside plans an agent will actually take makes the queue's banner false.
    managed = [p for p in all_plans if p.auto_generated]
    tank = [p for p in all_plans if not p.auto_generated]

    lines: List[str] = [
        "<!-- GENERATED by scripts/docs/rebuild_todo_readme.py — do not hand-edit. -->",
        "",
        "# Holding Tank — Unfinished Work",
        "",
        "Implementation plans that are **not finished**. The mirror image of",
        "[`../implementations/`](../implementations/README.md), which archives completed work.",
        "A plan lives here while it is shelved, in progress, planned, blocked, in review, or a",
        "deferred follow-up — and **moves** to the archive when it is done.",
        "",
        "**Primary audience**: agents and maintainers deciding what to pick up next, and anyone",
        "checking whether a capability already exists (parked) before rebuilding it.",
        "",
        "**Machine-readable index**: [`../todo_index.json`](../todo_index.json).",
        "",
        f"**{len(tank)} open plans** · **{len(managed)} agent-managed**",
        "",
        "---",
        "",
    ]

    for status, heading, blurb in STATUS_HEADINGS:
        items = [p for p in tank if p.shelf_status == status]
        if not items:
            continue
        lines += [f"## {heading}", "", f"_{blurb}_", ""]
        if status == "ready":
            lines += list(_ready_table(items))
            lines += ["", "> Lower `Queue-Order` runs earlier; `—` means unnumbered, which sorts last.", ""]
        elif status == "in-review":
            lines += list(_review_table(items))
            lines += [""]
        elif status in plans.GATED:
            lines += list(_gated_table(items))
            lines += [""]
        else:
            lines += list(_plain_table(items))
            lines += [""]

    if managed:
        lines += [
            "## ⚙️ Agent-Managed (Derived — Not a Queue)",
            "",
            "_Rewritten wholesale by a scheduled job. Never hand-edit one, and never file one to_",
            "_the archive — the producing job would recreate it and leave a zombie behind._",
            "",
        ]
        lines += list(_plain_table(managed))
        lines += [""]

    lines += [
        "---",
        "",
        "## Lifecycle",
        "",
        "```",
        "planned ──▶ ready ──▶ in-progress ──▶ in-review ──▶ docs/implementations/",
        "   │                                      │",
        "   └────────▶ blocked / shelved ──────────┘   (deferred follow-ups stay here)",
        "```",
        "",
        "Statuses, gates and the queue numbering are defined in",
        "[`docs/rules/docs.md`](../rules/docs.md). File a finished plan with",
        "`dev docs file <slug> --category <category>` — never a plain `mv`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if stale; write nothing")
    args = parser.parse_args()

    rendered = build()
    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != rendered:
            fail("docs/TODO/README.md is stale — run `dev docs index`")
            return 1
        ok("docs/TODO/README.md is current")
        return 0

    README_PATH.parent.mkdir(parents=True, exist_ok=True)
    README_PATH.write_text(rendered, encoding="utf-8")
    ok("wrote docs/TODO/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
