#!/usr/bin/env python3
"""Rebuild ``docs/implementations/README.md`` from the generated index.

Reads ``implementation_index.json`` rather than re-scanning the tree, so the
README cannot describe a set of documents the index does not. Grouped by
category, and within a category by ``agent_value`` then recency — the ordering a
reader wants is "what should I read before touching this", not the alphabet.

Usage:  python scripts/docs/rebuild_impl_readme.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.output import die, fail, ok  # noqa: E402
from scripts.paths import IMPL_DIR, PROJECT_ROOT  # noqa: E402

INDEX_PATH = PROJECT_ROOT / "docs" / "implementation_index.json"
README_PATH = IMPL_DIR / "README.md"

VALUE_BADGE = {3: "⭐⭐⭐", 2: "⭐⭐", 1: "⭐"}


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").strip() or "—"


def build() -> str:
    if not INDEX_PATH.exists():
        die("implementation_index.json missing — run gen_impl_index.py first")
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    entries = index["implementations"]

    lines = [
        "<!-- GENERATED by scripts/docs/rebuild_impl_readme.py — do not hand-edit. -->",
        "",
        "# Implementation Archive — Completed Work",
        "",
        "Completed plans, moved here from [`../TODO/`](../TODO/README.md) when they shipped.",
        "This is the record of **why the system is the way it is**: the decisions, the options",
        "that were dropped, and the constraints that shaped what landed.",
        "",
        "**Read before modifying a system**, not after. The `Value` column says how much:",
        "",
        "| Value | Meaning                                                     |",
        "| ----- | ----------------------------------------------------------- |",
        "| ⭐⭐⭐ | Key design decisions — read before modifying this system    |",
        "| ⭐⭐   | Useful debugging and rationale context                      |",
        "| ⭐     | Historical only                                             |",
        "",
        "**Machine-readable index**: [`../implementation_index.json`](../implementation_index.json).",
        "",
        f"**{index['count']} archived plans** across {len(index['by_category'])} categories.",
        "",
        "---",
        "",
    ]

    for category in sorted(index["by_category"]):
        items = [e for e in entries if e["category"] == category]
        items.sort(key=lambda e: (-int(e.get("agent_value", 1)), str(e.get("completed", "")), e["slug"]))
        lines += [
            f"## {category.replace('-', ' ').replace('_', ' ').title()}",
            "",
            "| Value | Plan | Completed | Summary |",
            "| ----- | ---- | --------- | ------- |",
        ]
        for entry in items:
            rel = Path(entry["path"]).relative_to("docs/implementations")
            badge = VALUE_BADGE.get(int(entry.get("agent_value", 1)), "⭐")
            lines.append(
                f"| {badge} | [{_cell(entry['title'])}]({rel.as_posix()}) "
                f"| {_cell(entry.get('completed', ''))} | {_cell(entry.get('summary', ''))} |"
            )
        lines.append("")

    lines += [
        "---",
        "",
        "File a finished plan with `dev docs file <slug> --category <category>`, which does the",
        "`git mv` and every regeneration in one step. Then repoint what cited it:",
        "`dev check doc-refs` and `dev check doc-links`. **Repoint, never delete** — those",
        "links are prose that records why the docs say what they say.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if stale; write nothing")
    args = parser.parse_args()

    rendered = build()
    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != rendered:
            fail("docs/implementations/README.md is stale — run `dev docs index`")
            return 1
        ok("docs/implementations/README.md is current")
        return 0

    README_PATH.parent.mkdir(parents=True, exist_ok=True)
    README_PATH.write_text(rendered, encoding="utf-8")
    ok("wrote docs/implementations/README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
