#!/usr/bin/env python3
"""Every subject in this range is one Release Please can read.

Not a style lint. The conventional-commit rule is enforced locally by the
`commit-msg` hook in `.pre-commit-config.yaml`, which binds only contributors
who ran `pre-commit install` — not a web-UI commit, not a merge made in the
GitHub interface, not a machine. And the rule is not decorative here, because
this tree wires those subjects to something:

> **Release Please builds the changelog and decides the version bump by parsing
> commit subjects.** A subject it cannot parse is not rejected — it is
> *ignored*. The change ships with no changelog entry, and if it was the only
> `fix` in the range, with no release at all.

So this asks one question, and it is a contract between two components of this
tree rather than a matter of taste: **will the release automation see this
commit?** A subject that reads badly and parses is none of its business.

## The vocabulary is read, never listed

`changelog-sections` in `.github/release-please-config.json` IS the set of types
this repository has configured, so it is the set this reads. A type that parses
as conventional but has no section configured is one whose commits are invisible
in the changelog — the same defect the unparseable ones have, and a list here
would disagree with the config the day somebody edits one of them.

## Scope, and why it is not "all history"

The range only. A repository adopting this template has history written under
whatever rule it had before, and a gate that is red on arrival is one people
learn to ignore — so this can only ever see commits the current change adds.
That makes it a ratchet at 0 for a fresh scaffold by construction, rather than
by a baseline somebody has to maintain.

Merge commits are excluded **structurally**, by parent count, not by matching
"Merge pull request" — a subject-shaped exemption is one somebody's branch name
can defeat, and it would silently exempt real commits.

Usage:  python scripts/check_commit_subjects.py [--range A..B] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

# Bootstrap only: put the package on sys.path so `scripts.paths` — which
# owns every path below — can be imported. See scripts/paths.py.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.output import detail, emit, fail, item, ok, warn  # noqa: E402
from scripts.paths import GITHUB_DIR, PROJECT_ROOT  # noqa: E402

#: SCAFFOLD-OPTIONAL .github/release-please-config.json
#: Absent under `--versioning tag`, where the git tag is the version and nothing
#: parses these subjects. This file NAMES that path in order to handle its
#: absence, which is a different act from sending a reader to it.
RELEASE_CONFIG = GITHUB_DIR / "release-please-config.json"

#: `type(scope)!: description` — the conventional-commit subject, as Release
#: Please's parser reads it. The scope is optional, the `!` breaking marker is
#: optional, the space after the colon is not.
SUBJECT = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?: (?P<description>.+)$")


def configured_types() -> set:
    """The types this repository's Release Please config gives a section.

    Absent config is not an error and not a pass: without it there is no
    contract to check, and the caller is told so rather than shown a green tick
    for a question nobody asked.
    """
    if not RELEASE_CONFIG.exists():
        return set()
    config = json.loads(RELEASE_CONFIG.read_text(encoding="utf-8"))
    sections = []
    for package in (config.get("packages") or {}).values():
        sections += package.get("changelog-sections") or []
    return {section["type"] for section in sections if "type" in section}


def subjects(commit_range: str):
    """`(sha, subject)` for every non-merge commit in the range, or None.

    `--no-merges` is the structural exclusion: a merge commit's subject is
    generated by whoever pressed the button and describes no change of its own.
    Matching "Merge pull request" instead would be an exemption any branch name
    could claim, and it would silently excuse real commits.

    **None means git could not resolve the range**, which is not an empty range
    and must not be reported as one. The first draft returned `[]` for both and
    printed `0 subject(s) ... are readable` against a range that did not exist —
    a green tick over a set nothing had looked at, which is the exact failure
    this file is here to prevent, committed by the file itself.
    """
    result = subprocess.run(
        ["git", "log", "--no-merges", "--format=%h\x1f%s", commit_range],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return [tuple(line.split("\x1f", 1)) for line in result.stdout.splitlines() if "\x1f" in line]


def unreadable(inspected: list, types: set) -> list:
    """`(sha, subject, why)` for each subject Release Please will not use."""
    findings = []
    for sha, subject in inspected:
        match = SUBJECT.match(subject)
        if not match:
            findings.append((sha, subject, "does not parse as `type(scope): description`"))
        elif match.group("type") not in types:
            findings.append((sha, subject, f"type `{match.group('type')}` has no section in the config"))
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--range",
        dest="commit_range",
        default="",
        help="git range to inspect. Empty means HEAD alone, which is what a local run wants.",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable payload on stdout")
    args = parser.parse_args()

    commit_range = args.commit_range or "-1"
    types = configured_types()
    inspected = subjects(commit_range)

    if inspected is None:
        if args.json:
            emit({"range": commit_range, "error": "git could not resolve this range"})
        fail(f"git could not resolve `{commit_range}`")
        detail("A shallow clone cannot see the base commit — CI checks this out with")
        detail("`fetch-depth: 0` for that reason. An unresolvable range is an error and")
        detail("never a pass: reporting it as zero subjects is a green tick over nothing.")
        return 1

    findings = unreadable(inspected, types) if types else []

    if args.json:
        emit(
            {
                "range": commit_range,
                "inspected": len(inspected),
                "configured_types": sorted(types),
                "unreadable": [{"sha": s, "subject": t, "why": w} for s, t, w in findings],
            }
        )

    if not types:
        warn(f"no changelog-sections in {RELEASE_CONFIG.relative_to(PROJECT_ROOT)} — nothing to check against")
        detail("Release Please is not configured to read commit subjects here, so this")
        detail("check has no contract to enforce. That is a finding about the config.")
        return 0

    if findings:
        fail(f"{len(findings)} subject(s) Release Please will silently ignore:")
        for sha, subject, why in findings:
            item(f"{sha}  {subject}")
            detail(f"       {why}")
        detail()
        detail("An unreadable subject is not rejected by the release automation — it is")
        detail("skipped. No changelog entry, and no version bump if this was the only")
        detail(f"releasing change. Configured types: {', '.join(sorted(types))}.")
        detail("Reword with `git commit --amend` or an interactive rebase.")
        return 1

    # The count is reported because the alternative is a green tick over an
    # empty range, and a range CAN legitimately be empty — a push of nothing but
    # merge commits contains no subject this asks about. That is a different
    # fact from an unresolvable range above, and the two must not print alike.
    if not inspected:
        ok(f"no non-merge commits in {commit_range} — nothing to check")
        return 0
    ok(f"{len(inspected)} subject(s) in {commit_range} are readable by Release Please")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
