#!/usr/bin/env python3
"""Every commit in this range passes the `commit-msg` hook.

The hook is the rule; this is the hook applied to a *range* instead of to one
message. It exists because of where the hook cannot reach:

> `.pre-commit-config.yaml` installs `commit-msg` locally, so it binds whoever
> ran `pre-commit install`. It does not bind a web-UI commit, a merge made in
> the GitHub interface, a machine, or a contributor who never installed it —
> and those are exactly the commits nobody local is going to catch.

## Why this is not `check_commit_subjects.py`

They look like the same check and they are two contracts, which is why both
exist and why neither subsumes the other.

`check_commit_subjects.py` asks whether **Release Please** can parse a subject,
reading its vocabulary out of `.github/release-please-config.json`. This tree is
`--versioning tag` and ships no such config, so that script correctly finds no
contract and checks nothing — it prints *"nothing to check against"* and exits
0, on every commit, forever. Wiring it into CI here would be a green step that
has never looked at anything.

This one asks whether the subject is a **conventional commit with one subject
line**, which is a house rule that holds whether or not anything generates a
changelog from it. In a tag-versioned tree it is the only one of the two that
can fail.

## The vocabulary is not here, and that is the point

Nothing in this file knows what a valid type is. It shells out to
`scripts/hooks/conventional-commit-check.sh` — the same script the hook runs,
against the same message — so a range check and a local commit cannot disagree.
That script already derives its vocabulary from the Release Please config where
one exists and falls back where it does not, and it explains why. A second copy
of that decision here is the drift this repository keeps finding: the hook's own
comments record a hardcoded list that disagreed with the config and let a
`style(lint):` subject pass locally and fail in CI.

So the division is: **the hook owns the rule, this owns the range.**

Usage:  python scripts/check_commit_style.py [--range A..B] [--json]
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.check_commit_subjects import default_range, described  # noqa: E402
from scripts.output import detail, emit, fail, item, ok  # noqa: E402
from scripts.paths import PROJECT_ROOT, SCRIPTS_DIR  # noqa: E402

HOOK = SCRIPTS_DIR / "hooks" / "conventional-commit-check.sh"


def commits(commit_range: str) -> list | None:
    """`(sha, subject)` for each non-merge commit in the range, newest first.

    `None` means git could not resolve the range, which is not an empty range.
    Reporting an unresolvable range as zero commits is a green tick over a set
    nothing looked at — the failure `check_commit_subjects.py` documents having
    committed itself, so it is not repeated here.

    Merges are excluded for the reason they are excluded there: a merge subject
    is generated by whoever pressed the button and describes no change.

    **`-1` is a limit, not a range, and `rev-list` will not take it alone.**
    `check_commit_subjects.py` accepts it because `git log -1` defaults to HEAD;
    `git rev-list -1` has no default and exits non-zero, which this would then
    report as *"could not resolve"* — a hard failure on the exact branch CI
    takes when there is no base commit to diff against. So a leading `-` is
    given `HEAD` explicitly. Spelled out because the two commands differing on
    it is not obvious, and the caller passing `-1` is a workflow nobody runs by
    hand.
    """
    selector = [commit_range, "HEAD"] if commit_range.startswith("-") else [commit_range]
    result = subprocess.run(
        ["git", "rev-list", "--no-merges", "--format=%h\x1f%s", *selector],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    # `rev-list --format` emits a `commit <sha>` header line before each entry.
    return [tuple(line.split("\x1f", 1)) for line in result.stdout.splitlines() if "\x1f" in line]


def message(sha: str) -> str:
    """The full message, body included — the hook checks more than the subject."""
    return subprocess.run(
        ["git", "log", "-1", "--format=%B", sha],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    ).stdout


def rejected(inspected: list) -> list:
    """`(sha, subject, why)` for each commit the hook refuses.

    The hook's own stderr is the explanation, verbatim and untranslated. A
    paraphrase here would be a second opinion about a rule this file has
    deliberately not learned.
    """
    findings = []
    for sha, subject in inspected:
        with tempfile.NamedTemporaryFile("w", suffix=".msg", delete=False) as handle:
            handle.write(message(sha))
            path = handle.name
        try:
            result = subprocess.run(
                ["bash", str(HOOK), path],
                cwd=str(PROJECT_ROOT),
                capture_output=True,
                text=True,
            )
        finally:
            Path(path).unlink(missing_ok=True)
        if result.returncode != 0:
            why = (result.stdout + result.stderr).strip().splitlines()
            findings.append((sha, subject, why[0] if why else "rejected with no message"))
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--range",
        dest="commit_range",
        default="",
        help="git range to inspect. Empty means everything not yet on the upstream, "
        "which is what a push will send; HEAD alone if there is no upstream.",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable payload on stdout")
    args = parser.parse_args()

    if not HOOK.exists():
        fail(f"the commit-msg hook is missing: {HOOK}")
        detail("This check is that hook applied to a range. Without it there is no rule to")
        detail("apply, and passing would report a vocabulary nobody enforced.")
        return 1

    chosen = not args.commit_range
    commit_range = args.commit_range or default_range()
    inspected = commits(commit_range)

    if inspected is None:
        if args.json:
            emit({"range": commit_range, "error": "git could not resolve this range"})
        fail(f"git could not resolve `{commit_range}`")
        detail("A shallow clone cannot see the base commit — deepen it, which is why the")
        detail("gate job checks out with `fetch-depth: 0`. A force-push leaves the old base")
        detail("an orphan reachable from no ref, and no depth reaches that: check HEAD")
        detail("alone, or name a range that exists.")
        return 1

    findings = rejected(inspected)

    if args.json:
        emit(
            {
                "range": commit_range,
                "inspected": len(inspected),
                "findings": [{"sha": sha, "subject": subject, "why": why} for sha, subject, why in findings],
            }
        )
        return 1 if findings else 0

    if findings:
        fail(f"{len(findings)} of {len(inspected)} commit(s) in {described(commit_range, chosen)} fail the hook:")
        for sha, subject, why in findings:
            item(f"{sha}  {subject}")
            detail(f"    {why}")
        detail("")
        detail("The rule is `scripts/hooks/conventional-commit-check.sh`, which pre-commit")
        detail("installs as `commit-msg`. Run `pre-commit install` and these are caught")
        detail("before they are committed rather than after they are pushed.")
        return 1

    ok(f"{len(inspected)} commit subject(s) in {described(commit_range, chosen)} pass the hook")
    return 0


if __name__ == "__main__":
    sys.exit(main())
