#!/usr/bin/env python3
"""Every subject in this range is one Release Please can read.

Not a style lint. The conventional-commit rule is enforced locally by the
`commit-msg` hook in `.pre-commit-config.yaml`, which binds only contributors
who ran `pre-commit install` — not a web-UI commit, not a merge made in the
GitHub interface, not a machine. And the rule is not decorative here, because
this tree wires those subjects to something:

> **Release Please builds the changelog and decides the version bump by parsing
> commit subjects.** A subject it cannot parse is not rejected — it is
> *ignored*. The change ships with no changelog entry, and if it was the only
> `fix` in the range, with no release at all.

So this asks one question, and it is a contract between two components of this
tree rather than a matter of taste: **will the release automation see this
commit?** A subject that reads badly and parses is none of its business.

## The vocabulary is read, never listed

`changelog-sections` in `.github/release-please-config.json` IS the set of types
this repository has configured, so it is the set this reads. A type that parses
as conventional but has no section configured is one whose commits are invisible
in the changelog — the same defect the unparseable ones have, and a list here
would disagree with the config the day somebody edits one of them.

## Scope, and why it is not "all history"

The range only. A repository adopting this template has history written under
whatever rule it had before, and a gate that is red on arrival is one people
learn to ignore — so this can only ever see commits the current change adds.
That makes it a ratchet at 0 for a fresh scaffold by construction, rather than
by a baseline somebody has to maintain.

Merge commits are excluded **structurally**, by parent count, not by matching
"Merge pull request" — a subject-shaped exemption is one somebody's branch name
can defeat, and it would silently exempt real commits.

Usage:  python scripts/check_commit_subjects.py [--range A..B] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

# Bootstrap only: put the package on sys.path so `scripts.paths` — which
# owns every path below — can be imported. See scripts/paths.py.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.output import detail, emit, fail, item, ok, warn  # noqa: E402
from scripts.paths import GITHUB_DIR, PROJECT_ROOT  # noqa: E402

#: SCAFFOLD-OPTIONAL .github/release-please-config.json
#: Absent under `--versioning tag`, where the git tag is the version and nothing
#: parses these subjects. This file NAMES that path in order to handle its
#: absence, which is a different act from sending a reader to it.
RELEASE_CONFIG = GITHUB_DIR / "release-please-config.json"

#: `type(scope)!: description` — the conventional-commit subject, as Release
#: Please's parser reads it. The scope is optional, the `!` breaking marker is
#: optional, the space after the colon is not.
SUBJECT = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?: (?P<description>.+)$")


def configured_types() -> set:
    """The types this repository's Release Please config gives a section.

    Absent config is not an error and not a pass: without it there is no
    contract to check, and the caller is told so rather than shown a green tick
    for a question nobody asked.
    """
    if not RELEASE_CONFIG.exists():
        return set()
    config = json.loads(RELEASE_CONFIG.read_text(encoding="utf-8"))
    sections = []
    for package in (config.get("packages") or {}).values():
        sections += package.get("changelog-sections") or []
    return {section["type"] for section in sections if "type" in section}


def subjects(commit_range: str):
    """`(sha, subject)` for every non-merge commit in the range, or None.

    `--no-merges` is the structural exclusion: a merge commit's subject is
    generated by whoever pressed the button and describes no change of its own.
    Matching "Merge pull request" instead would be an exemption any branch name
    could claim, and it would silently excuse real commits.

    **None means git could not resolve the range**, which is not an empty range
    and must not be reported as one. The first draft returned `[]` for both and
    printed `0 subject(s) ... are readable` against a range that did not exist —
    a green tick over a set nothing had looked at, which is the exact failure
    this file is here to prevent, committed by the file itself.
    """
    result = subprocess.run(
        ["git", "log", "--no-merges", "--format=%h\x1f%s", commit_range],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return [tuple(line.split("\x1f", 1)) for line in result.stdout.splitlines() if "\x1f" in line]


def unreadable(inspected: list, types: set) -> list:
    """`(sha, subject, why)` for each subject Release Please will not use."""
    findings = []
    for sha, subject in inspected:
        match = SUBJECT.match(subject)
        if not match:
            findings.append((sha, subject, "does not parse as `type(scope): description`"))
        elif match.group("type") not in types:
            findings.append((sha, subject, f"type `{match.group('type')}` has no section in the config"))
    return findings


def default_range() -> str:
    """What is about to be pushed, or `HEAD` alone when git cannot say.

    The default used to be `-1` — HEAD alone — described as *what a local run
    wants*. It is not what the run that matters wants. `check pre-push` passes
    no `--range`, so a push of three commits validated one of them here and CI
    validated all three: **same gate, same name, two sets, and the larger one
    runs after the push.** A gate whose local and remote answers differ is worse
    than one that only runs remotely, because the green tick is doing work to
    stop somebody looking.

    `@{u}..HEAD` is the set the push will send. With no upstream — a branch
    whose first push this is — there is nothing to diff against and HEAD alone
    is the honest answer, which is the same fallback `ci.yml` makes for an
    all-zeros `before`. The chosen range is printed either way, because the
    defect being fixed here was two ranges that looked identical in the output.
    """
    resolved = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "@{u}"],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    )
    return "@{u}..HEAD" if resolved.returncode == 0 else "-1"


def described(commit_range: str, chosen: bool) -> str:
    """The range as a sentence, because `-1` is a git spelling and not English.

    `chosen` means *this script picked it*, and it gates the parenthetical
    rather than the range: `-1` from `default_range()` means there was no
    upstream, and `-1` from a caller means they asked for HEAD alone with an
    upstream possibly sitting right there. Same string, two different facts,
    and the explanation is only true for one of them.
    """
    if not chosen:
        return commit_range
    return {
        "-1": "HEAD alone (no upstream to compare against)",
        "@{u}..HEAD": "@{u}..HEAD (everything this push would send)",
    }.get(commit_range, commit_range)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--range",
        dest="commit_range",
        default="",
        help="git range to inspect. Empty means everything not yet on the upstream, "
        "which is what a push will send; HEAD alone if there is no upstream.",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable payload on stdout")
    args = parser.parse_args()

    chosen = not args.commit_range
    commit_range = args.commit_range or default_range()
    types = configured_types()
    inspected = subjects(commit_range)

    if inspected is None:
        if args.json:
            emit({"range": commit_range, "error": "git could not resolve this range"})
        fail(f"git could not resolve `{commit_range}`")
        detail("Two causes, and they take different remedies:")
        detail("  · a shallow clone cannot see the base commit — deepen it, which is why")
        detail("    CI checks out with `fetch-depth: 0`;")
        detail("  · the base is an ORPHAN, which a force-push leaves behind. It is")
        detail("    reachable from no ref, so there is nothing for a deeper fetch to")
        detail("    reach — check HEAD alone, or name a range that exists.")
        detail("An unresolvable range is an error and never a pass: reporting it as zero")
        detail("subjects is a green tick over nothing.")
        return 1

    findings = unreadable(inspected, types) if types else []

    if args.json:
        emit(
            {
                "range": commit_range,
                "inspected": len(inspected),
                "release_please_configured": RELEASE_CONFIG.exists(),
                "configured_types": sorted(types),
                "unreadable": [{"sha": s, "subject": t, "why": w} for s, t, w in findings],
            }
        )

    if not types:
        # **Two states, and they were reported as one.** An empty `types` means
        # either that there is no Release Please config — correct and expected
        # under `--versioning tag`, where the annotated git tag is the version
        # and nothing parses these subjects — or that there is one and it gives
        # no type a changelog section, which is a real finding about the config.
        #
        # Reported as a warning in both, so a tag tree warned on every run about
        # a file that must not exist, and said "that is a finding about the
        # config" 150 lines below the `RELEASE_CONFIG` comment stating the
        # absence is deliberate. Self-contradictory inside one file, and it
        # trains a reader to skip this script's warnings, which is the cost.
        #
        # This is the `absent` versus `empty` split `frontmatter.py` documents
        # and `check_skip_budget.py` documents: *"I could not read this" and
        # "this key is empty" are different answers, and only one of them can be
        # noticed.* node-zero's finding, from a `--versioning tag` tree.
        if not RELEASE_CONFIG.exists():
            ok(f"no {RELEASE_CONFIG.name} — this repository versions by annotated git tag")
            detail("Nothing parses commit subjects for a changelog here, so there is no")
            detail("contract for this check to enforce. Subject discipline is still enforced")
            detail("by the commit hook and the CI gate; only the changelog mapping is absent.")
            return 0
        warn(f"no changelog-sections in {RELEASE_CONFIG.relative_to(PROJECT_ROOT)} — nothing to check against")
        detail("Release Please is configured here and gives no commit type a changelog")
        detail("section, so every subject is silently ignored by the release automation.")
        detail("That is a finding about the config.")
        return 0

    if findings:
        fail(f"{len(findings)} subject(s) Release Please will silently ignore:")
        for sha, subject, why in findings:
            item(f"{sha}  {subject}")
            detail(f"       {why}")
        detail()
        detail("An unreadable subject is not rejected by the release automation — it is")
        detail("skipped. No changelog entry, and no version bump if this was the only")
        detail(f"releasing change. Configured types: {', '.join(sorted(types))}.")
        detail("Reword with `git commit --amend` or an interactive rebase.")
        return 1

    # The count is reported because the alternative is a green tick over an
    # empty range, and a range CAN legitimately be empty — a push of nothing but
    # merge commits contains no subject this asks about. That is a different
    # fact from an unresolvable range above, and the two must not print alike.
    if not inspected:
        ok(f"no non-merge commits in {described(commit_range, chosen)} — nothing to check")
        return 0
    ok(f"{len(inspected)} subject(s) in {described(commit_range, chosen)} are readable by Release Please")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
