#!/usr/bin/env python3
"""Render the editor's issue and pull-request views from ``scripts/lanes.py``.

The GitHub Pull Requests extension reads ``githubIssues.queries`` and
``githubPullRequests.queries`` out of ``.vscode/settings.json``. Those two keys
are the **read side of the capture lanes** — ``dev bug`` and ``dev task``
file into labels, and without a view per label the queues are write-only. The
template shipped the filing and no view of it for its whole life.

**Why generated rather than shipped as static JSON.** The query set is a function
of two things that vary per tree: which lanes exist, and whether anything drains
them. Both already have a home — ``scripts/lanes.py`` and
``scripts/reporting/jobs.py`` (SCAFFOLD-OPTIONAL scripts/reporting/jobs.py — the
job registry ships with the agentic tier; this file tests for it) — so a
hand-written query list would be a third
copy of the label set and a second copy of a schedule, which is the pair of
mistakes the two registries exist to remove. The "Everything Else" query is the one
that shows why: it is a *negation over every lane label*, so it is wrong the
moment a lane is added and right by construction if it is derived.

**Only the region between the markers is generated.** ``.vscode/settings.json``
is a file people put their own settings in, so this splices text between a BEGIN
and an END line rather than round-tripping the JSON. A round-trip would preserve
the keys and silently drop every comment in a JSONC file, which is the quiet kind
of damage — the file still parses and still works, and the reasons somebody wrote
down are gone.

**And it CREATES the file rather than the template shipping it, which is the
same argument one step earlier.** Shipping it as a template file meant a
``--force`` scaffold — the case ``AGENTS.md`` calls *the usual case* — replaced
whatever editor settings the repository already had. Measured, on a tree
carrying ``editor.formatOnSave`` and a strict type-checking mode: both gone, with
nothing said. Almost every other file this template ships is machinery, where a
collision is the adoption working; this one is the reader's own configuration,
and skeletor has a claim on exactly two keys of it. So an existing file keeps
every key and comment and gains a region; an absent one is written whole.

Usage:  python3 scripts/gen_vscode_queries.py [--check] [--json]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

# Bootstrap only: put the package on sys.path so `scripts.paths` — which owns
# every path below — can be imported. See scripts/paths.py.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.lanes import LANES, drain_note, job_registry, labels  # noqa: E402
from scripts.output import detail, emit, fail, item, ok  # noqa: E402
from scripts.paths import PROJECT_ROOT  # noqa: E402

SETTINGS = PROJECT_ROOT / ".vscode" / "settings.json"

BEGIN = "// ── BEGIN generated by `python3 scripts/gen_vscode_queries.py` ──"
END = "// ── END generated ──"

#: The extension substitutes these itself, from the checked-out remote and the
#: authenticated user. Spelling the org and repo here would bake this tree's
#: remote into a file every fork carries — the `checkout_path_literal` class,
#: one repository out.
REPO = "repo:${owner}/${repository}"
#: Deliberately not written inside an f-string, and this comment deliberately
#: does not spell why in full. The extension's token is `${user}`; escaping it
#: for an f-string doubles the braces, and a doubled brace is the scaffolder's
#: placeholder syntax — so the escaped form makes `render()` refuse this file
#: rather than ship a literal placeholder into somebody's settings. Writing the
#: escaped form *in a comment* fails identically, which is how this line was
#: found: the note explaining the hazard contained it. The strictness is right;
#: a plain string is the spelling that does not need it.
REVIEWER = "is:open review-requested:${user}"


def issue_queries() -> List[Dict[str, object]]:
    """One view per lane, then the two that make the set a partition.

    The partition is the load-bearing part. Without "All Other" an issue filed
    by hand — the ordinary case, since a human opening an issue in the browser
    picks no lane label — is in no view at all, and an issue tracker you cannot
    see all of is one people stop trusting and then stop using. Its query is
    built by negating the registry, so it stays a true complement for free.
    """
    queries: List[Dict[str, object]] = []
    for lane in LANES:
        queries.append(
            {
                "label": f"{lane.emoji} {lane.title} ({drain_note(lane)})",
                "query": f"is:open label:{lane.label} {REPO} sort:created-asc",
            }
        )
    negation = " ".join(f"-label:{name}" for name in labels())
    queries.append(
        {
            "label": "Everything Else",
            "query": f"is:open {negation} {REPO} sort:updated-desc",
        }
    )
    queries.append({"label": "All Open", "query": "", "groupBy": ["milestone"]})
    return queries


def pr_queries() -> List[Dict[str, object]]:
    """The three states a pull request is in here, plus the extension's own view.

    These are label-free and therefore true in any repository — they read
    `draft:` and `review-requested:`, which GitHub maintains. They are worth
    generating anyway because the first one's NAME is a fact about the tree: a
    tree with a job that opens pull requests unattended accumulates drafts
    overnight, and one without does not. Naming a pane "Overnight Drafts" in a
    tree that has no overnight anything is a small lie in the place a reader
    looks to orient, so it is derived rather than written.

    The order is the order you work them: what ran while you were asleep, what
    is asking to land, what is asking for you.
    """
    return [
        {
            "label": "Overnight Drafts" if _has_unattended_committer() else "Drafts (iterating)",
            "query": f"is:open draft:true {REPO} sort:created-asc",
        },
        {"label": "Ready to Merge", "query": f"is:open draft:false {REPO} sort:created-asc"},
        {"label": "Waiting For My Review", "query": f"{REPO} {REVIEWER}"},
        {"label": "Local Pull Request Branches", "query": "default"},
    ]


def _has_unattended_committer() -> bool:
    """Does any registered job touch the git tree on its own schedule?

    False at every tier that ships no job registry, which is the honest answer
    rather than a degraded one: a tree with no scheduler has nothing running
    overnight, so the drafts in it are the ones a person left open.

    The optional import lives in `scripts/lanes.py::job_registry`, which carries
    the reason and the static-checker limit. This used to be a second copy of
    that construct — and mind.head reported the limit from the copy rather than
    the original, which is what two homes buys you.
    """
    registry = job_registry()
    return registry is not None and any(getattr(job, "commits", False) for job in registry.JOBS)


#: These keys sit INSIDE the settings object, so every line after the first
#: carries the object's indent. The first line does not: `splice` replaces from
#: the marker itself, leaving whatever whitespace precedes it in place.
INDENT = "  "


def region() -> str:
    """The generated text, with a stable key order so a no-op run is a no-op diff."""
    blocks = [
        f'"{key}": {json.dumps(value, indent=2, ensure_ascii=False)}'
        for key, value in (
            ("githubIssues.queries", issue_queries()),
            ("githubPullRequests.queries", pr_queries()),
        )
    ]
    # No trailing comma after the last key, which is what makes the region
    # safe to sit last in the object — and it must sit last, because a
    # generated block that has to end in a comma cannot also be the final
    # member. Your own settings go ABOVE the BEGIN marker; the file says so.
    lines = [BEGIN, *",\n".join(blocks).splitlines(), END]
    return "\n".join([lines[0], *(f"{INDENT}{line}" for line in lines[1:])])


#: Written only when there is no file at all. Everything in it is addressed to
#: somebody opening the repository for the first time, which is why the two
#: sentences that matter — your keys go ABOVE the marker, the region is replaced
#: wholesale — are stated where the mistake would be made rather than in a doc.
HEADER = """{
  // sky.boss — shared editor settings, tracked on purpose.
  //
  // This is JSONC: comments and trailing commas are legal here, and VS Code
  // reads this file for everyone who opens the repository. Personal settings
  // belong in your user settings, not here.
  //
  // PUT YOUR OWN KEYS ABOVE THE BEGIN MARKER. Everything between the markers is
  // written by `python3 scripts/gen_vscode_queries.py` from `scripts/lanes.py`,
  // and is replaced wholesale on every run — a key you add inside the region is
  // lost the next time a lane changes. Everything outside them is yours and is
  // never touched, comments included.
  //
  // The two generated keys are the read side of the capture lanes: `dev bug`
  // and `dev task` file issues under labels, and these are the views that
  // show you the queues. Regenerate after adding a lane or a drainer job;
  // `dev check docs` fails if they have drifted apart.

"""


def ensure_region(text: str) -> str:
    """A settings file with somewhere to put the generated block.

    Three states, and the middle one is the whole reason this function exists:
    the region is already there (leave it), the file exists without one (add it
    before the closing brace, touching nothing else), or there is no file
    (write the header). The second is what an adopter with their own editor
    settings hits, and the alternative — shipping the file from the template —
    overwrote those settings without saying so.

    The insertion point is the LAST closing brace, found by scanning back from
    the end. A JSONC parser would be the tidier answer and would have to
    tolerate comments and trailing commas to read a file it is only locating a
    character in.
    """
    if BEGIN in text:
        return text
    closing = text.rfind("}")
    if closing == -1:
        raise SystemExit(
            f"{SETTINGS.relative_to(PROJECT_ROOT)} has no closing brace — "
            "it is not a settings object this can add a generated region to"
        )
    head = text[:closing].rstrip()
    # A comma only when there is a key to separate from — decided by asking
    # whether what is already there parses to an empty object, not by looking
    # at the last character. The first draft did look at the last character,
    # and needed a tuple ending `"e", "l"` to cover values spelled `true` and
    # `null`: a guess at JSON's grammar, wrong for anything it had not thought
    # of, in the one place a wrong answer produces a file the editor silently
    # refuses to load.
    #
    # The probe puts the brace on its OWN line, which is not a detail. Glued
    # onto `head` it lands on whatever the last line is, and when that is a
    # `//` comment — the shape EVERY fresh tree has, because `HEADER` ends in
    # one — `strip_comments` blanks the brace along with the comment, the parse
    # raises, and `_is_empty_object`'s "somebody's hand-edit is mid-flight"
    # fallback fires on the file this generator itself wrote a moment earlier.
    probe = head + "\n" + chr(125)
    if not _is_empty_object(probe):
        head = _with_comma(head)
    return f"{head}\n\n  {BEGIN}\n  {END}\n{text[closing:]}"


def _with_comma(head: str) -> str:
    """Separate the last member from the region, on the line that holds it.

    Appending to `head` puts the comma wherever the file happens to END, and in
    a JSONC file that is often a trailing comment — where a comma is inert, and
    the key above it is then not separated from the generated region at all.
    That is the file VS Code silently refuses to load: the exact failure
    `_is_empty_object` exists to prevent, reached through the other door. It
    needs a key AND a comment after it, which is why the fixture set missed it
    — it had the shape that triggers the misclassification and not the shape
    where the misclassification has a consequence.

    A line already ending in one is left alone. Trailing commas are legal here
    and this file's own header tells the reader so.
    """
    lines = head.splitlines()
    for index in range(len(lines) - 1, -1, -1):
        stripped = lines[index].strip()
        if not stripped or stripped.startswith("//"):
            continue
        if lines[index].rstrip().endswith(","):
            return head
        lines[index] = lines[index].rstrip() + ","
        return "\n".join(lines)
    return head


def strip_comments(text: str) -> str:
    """JSONC to something ``json`` will read. Whole-line ``//`` only.

    Enough for what this file does with it — deciding whether an object is
    empty, and the round-trip-free parse check the tests make. It is
    deliberately not a JSONC parser: a `//` inside a string value would be cut
    by anything cleverer written in one line, and this never needs to be.
    """
    return "\n".join("" if line.lstrip().startswith("//") else line for line in text.splitlines())


def _is_empty_object(text: str) -> bool:
    try:
        return json.loads(strip_comments(text)) == {}
    except ValueError:
        # Unparseable means somebody's hand-edit is mid-flight or the file is
        # not what this thinks it is. A comma is the answer that preserves an
        # existing key; the missing-comma direction destroys one.
        return False


def splice(text: str, generated: str) -> str:
    """Replace the marked region, leaving every other byte of the file alone."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            f"{SETTINGS.relative_to(PROJECT_ROOT)} has no generated region — "
            f"expected a line containing {BEGIN!r} and, after it, one containing {END!r}"
        )
    return text[:start] + generated + text[end + len(END) :]


def _is_ignored(path: Path) -> bool:
    """Does git ignore this path *and* not track it? ``False`` when git cannot say.

    `check-ignore` exits 0 for ignored, 1 for not, and non-zero-not-1 for "this
    is not a repository" — which is a scaffold before its first commit, and not
    a diagnosis worth printing. Silence is the right answer there: the caller
    falls through to the ordinary instruction, which is correct in that tree.

    **It consults the index, and that is the load-bearing half.** A tracked path
    reports *not ignored* even when a rule matches it, because tracking wins — so
    a file that is tracked and merely deleted from the working tree falls through
    to `create it`, correctly, and only a path that is ignored *and* untracked
    gets the other message. That conjunction is exactly the claim being made, and
    it comes free rather than being assembled here. Measured in both states.
    """
    result = subprocess.run(
        ["git", "-C", str(PROJECT_ROOT), "check-ignore", "-q", str(path)],
        capture_output=True,
    )
    return result.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is not current; write nothing")
    parser.add_argument("--json", action="store_true", help="machine-readable result on stdout")
    args = parser.parse_args()

    if not SETTINGS.exists():
        if args.check:
            rel = SETTINGS.relative_to(PROJECT_ROOT)
            fail(f"{rel} is missing")
            if _is_ignored(SETTINGS):
                # The two ways this file can be absent look identical from the
                # filesystem and have opposite remedies, and the wrong one is
                # the reassuring one: `create it` succeeds, this check passes,
                # and the next fresh clone is red again because the file was
                # never committed. mind.head reported it from a tree whose
                # `.gitignore` predated this generator. This template does NOT
                # ignore `.vscode/` — it ignores `.idea/` and stops — so the
                # collision is invisible here by construction, which is why the
                # probe is a `git` question rather than a rule about our own
                # ignore file.
                detail("...and your .gitignore ignores it, which is why a clean checkout has none.")
                detail("Generating it again will not change that. Decide which you want:")
                detail("  * tracked — un-ignore the path, generate, and commit it; or")
                detail("  * untracked — drop this check from `dev check docs`, and every")
                detail("    reader generates their own.")
                return 1
            detail("Create it with: python3 scripts/gen_vscode_queries.py")
            return 1
        SETTINGS.parent.mkdir(parents=True, exist_ok=True)
        SETTINGS.write_text(HEADER + "}\n", encoding="utf-8")

    current = ensure_region(SETTINGS.read_text(encoding="utf-8"))
    wanted = splice(current, region())
    drifted = wanted != current

    if args.json:
        emit({"file": str(SETTINGS.relative_to(PROJECT_ROOT)), "drifted": drifted, "checked": args.check})
        return 1 if (drifted and args.check) else 0

    if not drifted:
        ok(f"{SETTINGS.relative_to(PROJECT_ROOT)} is current — {len(LANES)} lane(s)")
        return 0

    if args.check:
        fail(f"{SETTINGS.relative_to(PROJECT_ROOT)} is stale")
        detail("Regenerate with: python3 scripts/gen_vscode_queries.py")
        return 1

    SETTINGS.write_text(wanted, encoding="utf-8")
    ok(f"wrote {SETTINGS.relative_to(PROJECT_ROOT)}")
    for lane in LANES:
        item(f"{lane.emoji} {lane.title} — {lane.label} ({drain_note(lane)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
