// Assemble the sky.boss design-system bundle.
//
// Unlike a CSS-native system, sky.boss's colour roles are NOT in any
// stylesheet: cli/theme.py owns them and the server injects them into the page
// at runtime. So tokens.css is GENERATED by asking theme.py, never transcribed
// — a hand-copied hex here would be the second palette that module exists to
// prevent, and a sky-boss test fails on a hex outside it.
import { writeFileSync, copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

const REPO = '/home/jeston/skyrow.labs/sky-boss';
const OUT = process.argv[2];
mkdirSync(OUT, { recursive: true });

// --- tokens, straight out of theme.py ------------------------------------
const root = execFileSync(join(REPO, '.venv/bin/python'),
  ['-c', "import sys; sys.path.insert(0,'.'); from cli.theme import css_root; print(css_root())"],
  { cwd: REPO, encoding: 'utf8' }).trim();
if (!/^:root\{--sb-bg:#/.test(root)) throw new Error('theme.py did not emit a :root block: ' + root.slice(0, 80));

// One property per line, so the file is readable and diffable.
const pretty = root.replace(/^:root\{/, '').replace(/\}$/, '')
  .split(';').filter(Boolean).map((d) => `  ${d.trim()};`).join('\n');

writeFileSync(join(OUT, 'tokens.css'), `/* The colour roles, generated from cli/theme.py — the single module allowed to
 * name a hex. Do not edit: regenerate with .design-sync/scripts/build.mjs.
 *
 * --sb-scale is the one number the whole surface is measured in: every size in
 * sb.css is rem, and 1rem = 4px x this. 1.15 is what \`sb ui\` ships as its
 * default. The stylesheet falls back to 1 if it is absent.
 */
:root {
${pretty}

  --sb-scale: 1.15;
}
`);

// --- the stylesheet, verbatim --------------------------------------------
copyFileSync(join(REPO, 'cli/canvas/static/sb.css'), join(OUT, 'sb.css'));

writeFileSync(join(OUT, 'styles.css'), `/* sky.boss — the canvas design system.
 *
 * tokens.css first (the roles sb.css reads), then the stylesheet itself, which
 * derives every tint from those roles with color-mix and every size from
 * --sb-scale. Nothing else: sb.css is the whole surface.
 */
@import url("./tokens.css");
@import url("./sb.css");
`);

const kb = (p) => (readFileSync(join(OUT, p)).length / 1024).toFixed(1) + ' KB';
console.log(JSON.stringify({ tokens: pretty.split('\n').length, sbCss: kb('sb.css'), stylesCss: kb('styles.css') }, null, 2));
